global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "python-app"
    static_configs:
      - targets: ["host.docker.internal:5000"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "node-app"
    static_configs:
      - targets: ["host.docker.internal:3000"]
    metrics_path: /metrics
    scrape_interval: 30s

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["host.docker.internal:9187"]
    metrics_path: /metrics
    scrape_interval: 15s
