- name: Clone application repository
  git:
    repo: https://github.com/nelson-ngumo/DevOps-Assignment.git
    dest: /opt/devops-app
    force: yes

- name: Copy environment file
  copy:
    src: /home/nelson-ngumo/DevOps-Assignment/.env
    dest: /opt/devops-app/.env

- name: Copy environment file to docker directory
  shell: cp /opt/devops-app/.env /opt/devops-app/docker/.env
  become: yes

- name: Start application services
  shell: cd /opt/devops-app/docker && docker-compose up -d
  become: yes