---
- name: Install git
  apt:
    name: git
    state: present
  become: yes

- name: Remove existing app directory
  file:
    path: /opt/devops-app
    state: absent
  become: yes

- name: Clone application repository
  git:
    repo: https://github.com/Ngumonelson123/DevOps-Assignment.git
    dest: /opt/devops-app
    force: yes
    accept_hostkey: yes
  become: yes
  timeout: 60

- name: Copy environment file
  copy:
    src: .env
    dest: /opt/devops-app/.env
    mode: '0644'
  become: yes

- name: Copy environment file to docker directory
  copy:
    src: /opt/devops-app/.env
    dest: /opt/devops-app/docker/.env
    remote_src: yes
    mode: '0644'
  become: yes

- name: Start application services
  shell: cd /opt/devops-app/docker && docker-compose up -d
  become: yes

- name: Start monitoring services
  shell: cd /opt/devops-app/monitoring && docker-compose up -d
  become: yes

- name: Wait for services to be ready
  wait_for:
    port: "{{ item }}"
    host: "{{ ansible_default_ipv4.address }}"
    delay: 10
    timeout: 60
  loop:
    - 3000
    - 5000
    - 3001
    - 9090
